remote_theme: jasongrimes/jekyll-chapterbook

title: CS201 - Introduction to Programming with Python
longtitle: CS201 - Introduction to Programming with Python - KAUST Spring 2023
author: Malek Smaoui
email: Malek.Smaoui@kaust.edu.sa
description: >
  Lecture materials for CS201 - Introduction to Programming with Python - KAUST Spring 2023

# If baseurl_canonical is set, 
# a <link rel="canonical"> tag will be added to the head of each page,
# to disambiguate links for search engines.
baseurl_canonical:

# A copyright notice will be shown at the bottom of each page,
# with the current year and the author name.
# Set a url to link to a copyright page.
# Set a start_year to have the copyright render as "start_year - current_year" (if the years are different)
# Set copyright: false to disable.
copyright:
  start_year: 2023
  url: /book.html

# Customize the link favicon in header. Will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path: assets/gitbook/images/favicon.ico

#
# Navigation menus
#

# Breadcrumbs for book contents.
# The book and contents pages need to be made manually.
# All "url" variables should have a leading slash.
bookcrumbs:
  book_url: /book.html
  contents_url: /contents.html
  book_icon: assets/gitbook/images/apple-touch-icon-precomposed-152.png

# Links shown above the TOC in the sidebar
# All "url" variables should have a leading slash.
sidebar_nav_top:
# - label: Jekyll Chapterbook Theme
#   url: /index.html

# Links shown below the TOC in the sidebar
# All "url" variables should have a leading slash.
sidebar_nav_bottom:
# - label: Draft outline
#   url: /outline.html
# - label: Fork at GitHub
#   url: https://github.com/jasongrimes/jekyll-chapterbook/fork

# Navigation shown at the bottom of the page
# All "url" variables should have a leading slash.
bottom_nav:
- label: Home
  url: /index.html
- label: Book
  url: /book.html
- label: GitHub
  url: https://github.com/jasongrimes/jekyll-chapterbook
- label: Codingrooms
  url: https://codingrooms.com


# Whether to show chapter headings as a table of contents at the top of each chapter page.
# Override in page front matter with disable_toc: true
in_chapter_toc:
  enabled: true
  h_min: 2
  h_max: 3

# Whether to show chapter heading sub-navigation beneath the active chapter in the sidebar.
# Override in page front matter with disable_toc: true
sidebar_toc:
  enabled: false
  h_min: 2
  h_max: 3

# 
# End navigation menus
#

# Show a link to edit each page on GitHub
github_edit:
  enabled: false
  base_url: 

# Custom CSS
extra_css:

# Chapters can be hidden from navigation by adding ".draft" to the index at the start of their filename.
# (For example, rename 010-introduction.md to 010.draft-introduction.md)
#
# To make the drafts appear in the navigation in development environments,
# set show_drafts_in_dev to true.
show_drafts_in_dev: false





exclude:
  - _drafts
  - tmp

page_width: 800px

destination: ./_site
incremental: false
regenerate: true

plugins:
#  - jekyll-feed
  - jekyll-readme-index
#  - jemoji

collections:
  chapters:
    output: true
  pages:
    output: true
    permalink: /:slug:output_ext


defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
      permalink: /:slug:output_ext

# Markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true
syntax_highlighter_style: colorful
markdown_ext:     markdown,mkdown,mkdn,mkd,md
