name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2.2"
        bundler-cache: true
    - name: Install and Build
      run: |
        export JEKYLL_ENV=production
        bundle exec jekyll build --lsi
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _site
